/* eslint-disable no-unused-vars */
export enum ENUM_TASK_STATUS {
    PRIVATE = 'PRIVATE',
    OPEN = 'OPEN',
    ASSIGNED = 'ASSIGNED',
    IN_PROGRESS = 'IN_PROGRESS',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED',
}

export enum ENUM_SCHEDULE_TYPE {
    FIXED_DATE_AND_TIME = 'FIXED_DATE_AND_TIME',
    FLEXIBLE = 'FLEXIBLE',
}

export const ENUM_SERVICE_TYPE = {
    SNOW_PLOWING: 'SNOW_PLOWING',
    SNOW_SHOVELING: 'SNOW_SHOVELING',
    SALTING_DE_ICING: 'SALTING_DE_ICING',
    LAWN_MOWING: 'LAWN_MOWING',
    LANDSCAPING: 'LANDSCAPING',
    SEASONAL_CONTRACTS: 'SEASONAL_CONTRACTS',
};
