/* eslint-disable no-unused-vars */
export enum ENUM_TASK_STATUS {
    PRIVATE = 'PRIVATE',
    OPEN = 'OPEN',
    ASSIGNED = 'ASSIGNED',
    IN_PROGRESS = 'IN_PROGRESS',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED',
}

export enum ENUM_SCHEDULE_TYPE {
    FIXED_DATE_AND_TIME = 'FIXED_DATE_AND_TIME',
    FLEXIBLE = 'FLEXIBLE',
}
