export const ENUM_IDENTIFICATION_DOCUMENT_TYPE = {
    PASSPORT: 'PASSPORT',
    NATIONAL_ID: 'NATIONAL_ID',
    DRIVER_LICENSE: 'DRIVER_LICENSE',
    VOTER_ID: 'VOTER_ID',
};
export const ENUM_SERVICE_TYPE = {
    SNOW_PLOWING: 'SNOW_PLOWING',
    SNOW_SHOVELING: 'SNOW_SHOVELING',
    SALTING_DE_ICING: 'SALTING_DE_ICING',
    LAWN_MOWING: 'LAWN_MOWING',
    LANDSCAPING: 'LANDSCAPING',
    SEASONAL_CONTRACTS: 'SEASONAL_CONTRACTS',
};
